image : mcr.microsoft.com/dotnet/sdk:5.0


stages:
  - build
  - release
  - test

build:
  stage: build
  tags:
    - sopro
  only:
    - master
  script:
    - dotnet build Abgaben/Uebungsblatt05/Musterloesung/Team14/Team14.csproj

release:
  stage: build
  tags:
    - sopro
  only:
    - master
  artifacts:
    paths:
      -   publishFolder/
  script:
    - dotnet publish Abgaben/Uebungsblatt05/Musterloesung/Team14/Team14.csproj


test:
  stage: test
  only:
    - master
  artifacts:
    paths:
      -  Abgaben/Uebungsblatt06/Musterlösung/Tests
  script:
    - dotnet test
