image : mcr.microsoft.com/dotnet/sdk:5.0


stages:
  - build
  - test
#  - deploy

build:
  stage: build
  tags:
    - sopro
  only:
#    - master
    - Staging
  script:
#    - dotnet build Abgaben/Uebungsblatt06/Musterlösung/Team14/Team14.csproj
     - dotnet build Team14-XCV/XCV.csproj



test:
  stage: test
  tags:
    - sopro
  only:
#    - master
    - Staging
  script:
#    - dotnet test Abgaben/Uebungsblatt06/Musterlösung/Tests/Tests.csproj
    - dotnet test Tests/Tests.csproj

#deploy:
#  stage: deploy
#  tags:
#    - sopro
#  only:
#    - staging
#  script:
#    - dotnet publish -c Release Team14-XCV/XCV.csproj
#    - docker build -t counter-image -f Dockerfile .
    
