image : mcr.microsoft.com/dotnet/sdk:5.0


stages:
  - build
  - test
#  - deploy

# baut das Projekt
build:
  stage: build
  tags:
    - sopro
  only:
    - Staging
  script:
     - dotnet build Team14-XCV/XCV.csproj


# lässt Testprogramm über das Projekt laufen
test:
  stage: test
  tags:
    - sopro
  only:
    - Staging
  script:
    - dotnet test Tests/Tests.csproj

# wird akiviert sobald Docker mit der Datenbank funktioniert
# Baut eine Release-Version des Projekts und ein DockerImage
#deploy:
#  stage: deploy
#  tags:
#    - sopro
#  only:
#    - staging
#  script:
#    - dotnet publish -c Release Team14-XCV/XCV.csproj
#    - docker build -t xcv-image -f Dockerfile .
    
