image : mcr.microsoft.com/dotnet/sdk:5.0


stages:
  - build
  - test

build:
  stage: build
  tags:
    - sopro
  only:
    - master
  script:
    - dotnet build Abgaben/Uebungsblatt06/Musterlösung/Team14/Team14.csproj



test:
  stage: test
  tags:
    - sopro
  only:
    - master
  script:
    - dotnet test Abgaben/Uebungsblatt06/Musterlösung/Tests/Tests.csproj
